version: '3.8'

services:
  node-back:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app

  database:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:? postgres user name is needed}
      POSTGRES_PASSWORD: ${DB_PASSWORD:? postgres password is needed}
      POSTGRES_DB: ${DB_NAME:? postgres database name is needed}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
